import React from 'react';
import Head from 'next/head';
import Header from '../components/header/header';

interface Props {
  children: React.ReactNode
}

const MainLayout: React.FC<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="container py-5">
        {children}
      </main>
    </div>
  );
};

export default MainLayout;